[package]
name = "exam-gen"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
clap = { version = "4.0", features = ["derive"] }
serde = { version = "1.0.228", features = ["derive"] }
toml = "0.9.7"
itertools = "0.14.0"
rand = "0.10.0-rc.0"
